name: ossos_test
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.2.1+1
  connectivity_plus: ^4.0.1
  cached_network_image: ^3.2.3
  get: ^4.6.5
  oktoast: ^3.3.1
  dartz: ^0.10.1
  get_it: ^7.6.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
